networks:
  job_opportunities:

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourPassword123
      - MSSQL_PID=Developer
      - MSSQL_AGENT_ENABLED=True
    networks:
      - job_opportunities

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.python
    ports:
      - 8888:8888
    volumes:
      - ./notebook/dev.ipynb:/home/notebook/dev.ipynb
      - ./data/job_opportunities.csv:/home/data/job_opportunities.csv
      - ./data/job_opportunities_diagram.png:/home/data/job_opportunities_diagram.png
    depends_on:
      - db
    networks:
      - job_opportunities
    command: jupyter notebook --ip=0.0.0.0 --port=8888 --allow-root --notebook-dir=/home/ --no-browser --NotebookApp.token=''
